# Generated by Django 2.0.7 on 2018-08-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
